### Register a user
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "email": "kenny@google.com",
    "password": "test12"
}

### Login a user
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "kenny@google.com",
    "password": "test12"
}